# Generated by Django 4.2 on 2023-04-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_title', models.CharField(max_length=200)),
                ('employee_contact_info', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
