# Generated by Django 4.2 on 2023-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(max_length=500)),
                ('device_name', models.CharField(max_length=100)),
                ('device_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Device_Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField(max_length=500)),
                ('employee_id', models.IntegerField(max_length=500)),
                ('company_id', models.IntegerField(max_length=500)),
                ('checkout_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('checkout_condition', models.CharField(max_length=100)),
                ('return_condition', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'device_log',
            },
        ),
    ]
