# Generated by Django 4.2 on 2023-04-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_device_id_device_id_remove_device_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
    ]
