# Generated by Django 4.2 on 2023-04-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_employee_id_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_log',
            old_name='log_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='device_log',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='device_log',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='device_log',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='device_log',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
        migrations.AddField(
            model_name='device_log',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.device'),
        ),
        migrations.AddField(
            model_name='device_log',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
    ]
